---
- hosts: all
  become: true
  gather_facts: true
  tasks:
  - name: creating file on all app servers
    file:
        path: /tmp/ansible-job.txt
        state: touch
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0777
